### PR TITLE
Fix error on Redshift due to base_events_this_run using the transaction_id as partition key event if transactions are disabled (close #51)

### LINKED ISSUE #51: Fix error on Redshift due to base_events_this_run using the transaction_id as partition key event if transactions are disabled
## Describe the bug
In case transactions are disabled (`snowplow__disable_ecommerce_transactions`), the `transaction_id` is null and the partition by [statement here](https://github.com/snowplow/dbt-snowplow-ecommerce/blob/main/models/base/scratch/snowplow_ecommerce_base_events_this_run.sql#L127) then fails on Redshift as it uses the transaction_id (with the error “constant expressions are not supported in partition by clauses”). 

## Steps to reproduce
Disable transactions and run the package on Redshift.

## Expected results
No errors.

## Actual results
Error: `constant expressions are not supported in partition by clauses`

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

### PR DESCRIPTION
**Pull request by matus-tomlein**
## Description

Fixes the error in #51 by not using the `transaction_id` in the partition by columns in case transactions are disabled.

## What type of PR is this? (check all applicable)

- [x] 🐛 Bug Fix

## Related Tickets & Documents
Fixes #51 

## Checklist
- [x] ❗️ I have verified that these changes work on Redshift
- [ ] 💣 Is your change a breaking change?
- [x] 📖 I have updated the CHANGELOG.md

### Added tests?
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?
- [ ] 📓 internal package docs (ymls, macros, readme, if applicable)
- [ ] 📕 I have raised a [Snowplow documentation](https://github.com/snowplow/documentation) PR if applicable (Link here if required)
- [x] 🙅 no documentation needed

### CODE REVIEW

File: models/base/scratch/snowplow_ecommerce_base_events_this_run.sql [hunk 1]
```diff
@@ -124,7 +124,14 @@ field_extract as (
...
         *
-        , case when ecommerce_action_type != 'transaction' or ecommerce_action_type is null then 1 else row_number() over (partition by domain_sessionid, transaction_id order by derived_tstamp) end AS transaction_id_index
+        , case when ecommerce_action_type != 'transaction' or ecommerce_action_type is null
+            then 1 else row_number() over (
+                partition by domain_sessionid
+                {% if not var('snowplow__disable_ecommerce_transactions', false) -%}
+                    , transaction_id
+                {%- endif %}
+                order by derived_tstamp
+            ) end AS transaction_id_index
```
Comment (rlh1994) [inline models/base/scratch/snowplow_ecommerce_base_events_this_run.sql]: I'd probably make this whole thing an if-else block. There's not much point doing any of the compute if it isn't required?

Comment (matus-tomlein) [reply models/base/scratch/snowplow_ecommerce_base_events_this_run.sql]: Oh yeah, that's a good point, didn't realize what the CTE was actually doing 😅

**Review by rlh1994 — APPROVED** [review]
LGTM
